dashboards:
-
  name: "[Metrics Aerospike] Overview Yaml"
  description: A dashboard for Aerospike Metrics
  controls:
    - type: options
      label: Aerospike Namespace
      data_view: "metrics-*"
      field: aerospike.namespace
  panels:
  - type: markdown
    title: On-dashboard description of Aerospike Metrics
    hide_title: True
    content: |
      This dashboard provides an overview of Aerospike metrics, including node and namespace metrics.
      It includes links to the Aerospike documentation and community resources. See the integration page for setup instructions.
    grid: { x: 0, y: 0, w: 48, h: 3 }
  - type: links
    title: Links
    grid: { x: 0, y: 3, w: 48, h: 3 }
    description: Links to Aerospike documentation and other resources
    layout: horizontal
    links:
      - label: Overview
        dashboard: 0aa67124-5f70-a811-7ec5-063c196c5e6e
      - label: Node Metrics
        dashboard: ec958c2b-aefe-43ad-8864-60d0fe767280
      - label: Namespace Metrics
        dashboard: 70cf3a9f-94b5-4663-989b-b290aa94f43a
      - label: Vendor Documentation
        url: https://www.aerospike.com/docs/
      - label: Community Forum
        url: https://discuss.aerospike.com/

  - type: charts
    title: "Nodes by Namespace"
    description: A chart showing the number of nodes by namespace
    grid: { x: 0, y: 6, w: 16, h: 16 }
    chart:
      type: pie
      data_view: metrics-*
      slice_by:
        - field: aerospike.namespace
          type: values
          size: 5
      metric:
        aggregation: count
  - type: charts
    title: Free Memory by Node
    description: A chart showing the minimum free memory by node
    grid: { x: 16, y: 6, w: 32, h: 16 }
    chart:
      type: line
      data_view: metrics-*
      dimensions:
        - field: "@timestamp"
          type: date_histogram
      metrics:
        - aggregation: min
          field: aerospike.node.memory.free

  - title: Open Connections by Node
    type: charts
    description: A chart showing the number of open connections by node
    grid: { x: 16, y: 22, w: 32, h: 16 }
    chart:
      type: line
      data_view: metrics-*
      dimensions:
        - field: "@timestamp"
          type: date_histogram
      metrics:
        - aggregation: max
          field: aerospike.node.connection.open

