dashboard:
  title: Markdown Only
  description: ""
  panels:
    - panel:
        title: "Markdown Panel" 
        type: markdown
        grid: { x: 0, y: 0, w: 24, h: 15 }
        content: |
          # This is a basic markdown test